### ISSUE TITLE
MCX342A driver "mlx4_core" issues

### ISSUE THREAD

**Issue by ruixuntech** [pocopico/rp-ext#32]
When installing 918+42218 based on ESXI, if the driver contains vmxnet3 and mlx4_core, vmxnet3 will not work

**Comment by ruixuntech** [comment]
mlx4_core：Handles low-level functions like device initialization and firmware commands processing. Also controls resource allocation so that the InfiniBand, Ethernet and FC functions can share a device without interfering with each other.
mlx4_en：Handles Ethernet specific functions and plugs into the netdev mid-layer.
This network card is divided into ib mode and Ethernet mode. The official document points out that mlx4_core seems to be used in ib mode, so whether it is possible to add mlx4_en for Ethernet mode

**Comment by pocopico** [comment]
Added mlx4_en to the same extension. Now mlx4_core includes also mlx4_en

**Comment by ruixuntech** [comment]
After two days of testing, I found out that I don’t know what the reason is. My MCX312B-XCCT does not work properly on DS3615xs-7.0.1-42218, but it is on the official support list of Synology. Use the mlx4_core of your DS918+. Can't work, it all goes well in windows

**Comment by pocopico** [comment]
Well generally speaking 918 doesn’t support any pci-e network adapter. I’m afraid that you should stick on ds3615xs loader. And can you please send here a 

dmesg | grey mlx 
lsmod 
Ip a
ethtool -I ethx 
lspci -nq

**Comment by ruixuntech** [comment]
I will check its usage on DS3615xs today, at least I hope it works normally on DS3615xs, so that I can continue to test DS918+

**Comment by ruixuntech** [comment]
![1](https://user-images.githubusercontent.com/34979606/145923617-da4ddcda-1fd3-427d-82fe-06e69c002a5b.png)
![2](https://user-images.githubusercontent.com/34979606/145923621-2149702f-993c-4620-85d2-0450024a85cc.png)
![3](https://user-images.githubusercontent.com/34979606/145923623-97ff6509-4704-4c55-9ff4-c6b672e76ff7.png)

**Comment by ruixuntech** [comment]
I am sure that my hardware ID is 15b3:1003, I also loaded mlx4_core.ko and mlx4_en.ko, and it seems to be successful, but it does not appear in my network card list

**Comment by ruixuntech** [comment]
![企业微信截图_20211214105516](https://user-images.githubusercontent.com/34979606/145924694-0a5862d7-f5da-43f7-a54a-175a8c131360.png)
ethtool -I ethx
The magic is that although it is not in the list, it can be viewed through the tool

**Comment by ruixuntech** [comment]
Very good, now it can work on DS918+7.0.1-42218, I did the following:
insmod /usr/lib/modules/mlx4_core.ko
insmod /usr/lib/modules/mlx4_en.ko(must)
ifconfig eth1 up(must)
ifconfig eth2 up(must)
If I don’t do the following, it will be displayed using ethtool as in my previous answer, but it will not appear in the ifconfig list.
There is another problem. Since you updated the mlx4_core file 14 hours ago, an error will be prompted during compilation.
The only problem now is to let mlx4_core.ko and mlx4_en.ko be automatically loaded at boot, and automatically ifconfig eth1 up and ifconfig eth2 up

**Comment by ruixuntech** [comment]
![企业微信截图_20211214112808](https://user-images.githubusercontent.com/34979606/145927870-5db1e21b-ef43-453f-9f69-d18677044b11.png)

**Comment by ruixuntech** [comment]
![企业微信截图_20211214155649](https://user-images.githubusercontent.com/34979606/145956276-0d1d3119-35a3-4f7b-b6fa-5b787cf95eca.png)
There is a missing ","
I can compile successfully after repairing locally, but ds918+ is installed in an infinite loop

**Comment by pocopico** [comment]
Then that’s great news. I’ll update the extension.

**Comment by pocopico** [comment]
When any extension fail to load it will exit with error core 99 which is then misinterpreted as exit 99 by DSM and will fall into an install loop.

Fixed the extension typo and added an script on_os_load to try to bring up mlx4 interfaces up. Please update how this works for you.

**Comment by ruixuntech** [comment]
I used a new driver, DS918+ still cannot be searched, I guess it may be because there is no ifcofnig up

**Comment by pocopico** [comment]
Please be aware that on_os_boot script that will bring the interfaces up, will not run on the installation phase but only after successful install and OS boot

**Comment by ruixuntech** [comment]
What should I do, is there a way to use it during installation
